const { google } = require('googleapis');

exports.handler = async (event) => {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: 'Method Not Allowed' };
  }

  try {
    const { post, topic, accessToken } = JSON.parse(event.body);

    // Get credentials from environment
    const clientId = process.env.GOOGLE_CLIENT_ID;
    const clientSecret = process.env.GOOGLE_CLIENT_SECRET;

    if (!clientId || !clientSecret) {
      // Return demo response if credentials not configured
      return {
        statusCode: 200,
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          success: true,
          demo: true,
          message: 'Google Drive sync simulated - configure credentials for full functionality',
          data: {
            docId: 'demo-doc-' + Date.now(),
            sheetId: 'demo-sheet-' + Date.now(),
            folderId: 'socialpulse-content',
          },
        }),
      };
    }

    // Initialize OAuth client
    const oauth2Client = new google.auth.OAuth2(clientId, clientSecret);

    // Set credentials (in production, retrieve from secure storage)
    if (accessToken) {
      oauth2Client.setCredentials({
        access_token: accessToken,
      });
    } else {
      return {
        statusCode: 401,
        body: JSON.stringify({ error: 'Access token required' }),
      };
    }

    const drive = google.drive({ version: 'v3', auth: oauth2Client });

    // Create or get SocialPulse folder
    let folderId;
    const folderResponse = await drive.files.list({
      q: "name='SocialPulse Content' and mimeType='application/vnd.google-apps.folder'",
      fields: 'files(id, name)',
    });

    if (folderResponse.data.files.length > 0) {
      folderId = folderResponse.data.files[0].id;
    } else {
      const newFolder = await drive.files.create({
        resource: {
          name: 'SocialPulse Content',
          mimeType: 'application/vnd.google-apps.folder',
        },
        fields: 'id',
      });
      folderId = newFolder.data.id;
    }

    // Create Google Doc for the post content
    const docTitle = `${new Date().toISOString().split('T')[0]}-${topic.substring(0, 30)}`;
    const docContent = `
# Social Media Post - ${topic}

## Topic
${topic}

## Platform
${post.platform}

## Tone
${post.tone || 'Professional'}

## Content
${post.content}

---
Generated by SocialPulse AI Agent
Date: ${new Date().toLocaleString()}
    `.trim();

    // Create the document using Drive API (creates as HTML, can be converted)
    const docFile = await drive.files.create({
      resource: {
        name: `${docTitle}.txt`,
        mimeType: 'text/plain',
        parents: [folderId],
      },
      media: {
        mimeType: 'text/plain',
        body: docContent,
      },
      fields: 'id, webViewLink',
    });

    // Update the file to convert to Google Doc format
    const convertedDoc = await drive.files.update({
      fileId: docFile.data.id,
      resource: {
        mimeType: 'application/vnd.google-apps.document',
      },
    });

    // Update or create the master schedule sheet
    let sheetId;
    const sheetResponse = await drive.files.list({
      q: "name='SocialPulse Schedule' and mimeType='application/vnd.google-apps.spreadsheet'",
      fields: 'files(id, name)',
    });

    if (sheetResponse.data.files.length > 0) {
      sheetId = sheetResponse.data.files[0].id;
    } else {
      // Create new spreadsheet
      const newSheet = await drive.files.create({
        resource: {
          name: 'SocialPulse Schedule',
          mimeType: 'application/vnd.google-apps.spreadsheet',
          parents: [folderId],
        },
        fields: 'id',
      });
      sheetId = newSheet.data.id;

      // Initialize the sheet with headers
      const sheets = google.sheets({ version: 'v4', auth: oauth2Client });
      await sheets.spreadsheets.values.update({
        spreadsheetId: sheetId,
        range: 'Sheet1!A1:F1',
        valueInputOption: 'RAW',
        body: {
          values: [['ID', 'Date', 'Platform', 'Topic', 'Status', 'Drive Link']],
        },
      });
    }

    // Add row to the schedule sheet
    const sheets = google.sheets({ version: 'v4', auth: oauth2Client });
    await sheets.spreadsheets.values.append({
      spreadsheetId: sheetId,
      range: 'Sheet1',
      valueInputOption: 'RAW',
      insertDataOption: 'INSERT_ROWS',
      body: {
        values: [
          [
            post.id || Date.now().toString(),
            post.scheduledFor || new Date().toISOString(),
            post.platform,
            topic,
            post.status || 'Draft',
            convertedDoc.data.webViewLink,
          ],
        ],
      },
    });

    // Update post with Drive links
    const updatedPost = {
      ...post,
      driveDocId: convertedDoc.data.id,
      driveDocLink: convertedDoc.data.webViewLink,
      driveSheetId: sheetId,
      syncedAt: new Date().toISOString(),
    };

    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        success: true,
        data: {
          docId: convertedDoc.data.id,
          docLink: convertedDoc.data.webViewLink,
          sheetId,
          folderId,
        },
        post: updatedPost,
      }),
    };
  } catch (error) {
    console.error('Drive sync error:', error);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: error.message }),
    };
  }
};
